### ISSUE TITLE
Civi does not use undef

### ISSUE THREAD

**Issue by Alex6511** [BourbonWarfare/bwmf#145]

**Comment by AACO** [comment]
They don't have any defines, so they don't need to undefine anything... intended...

**Comment by TheCandianVendingMachine** [comment]
The fix here was misinformed really. Although it did fix the issue (Civilians got NVG's for no apparent reason as for they were not in any of the defines), it fixed it because `LINKED` was defined in `msv_csat_sama_hex.hpp` and `linkedItems[]` was pulling from that instead of `BASE_LINKED` and I don't know if pulling from the MSV File was intentional or not.

**Comment by AACO** [comment]
Maybe someone used that define, but there were never any defines in civ slots. If you just pull a random define without re-defining (or un-defining and defining) it first you get what you get.

If you added the undef file all you'd get is a different loadout error because that item you were using no longer exists in the preprocessor scope

We really don't even need undef files for the standard mission setup, it only helps with mikero tools rapping and compression
